app/tools/controllers.py
import flask

from app.tools import forms
from bin import estimator

tools = flask.Blueprint('tools', __name__)


@tools.route('/piping_beta/', defaults={"n": 5}, methods=["GET", "POST"])
@tools.route('/piping_beta/<n>', methods=["GET", "POST"])
def piping_beta(n):
    n = int(n)
    form = forms.BetaPipingForm()
    for _ in range(n):
        form.add_entry()

    if flask.request.method == "POST":
        if form.submit_field.data:
            form_data = form.rows
            n_rows = len(form_data)

            hourly_rate = form.salary_field.data
            bom_data = []
            item_time = 0
            item_cost = 0
            for r in range(0, n_rows):
                if form_data[r].quantity_field.data:
                    row_qty = form_data[r].quantity_field.data
                    if not row_qty in [float("inf"), float("-inf")]:
                        bom_data.append([r+1,
                                         form_data[r].item_field.data,
                                         form_data[r].diameter_field.data,
                                         form_data[r].schedule_field.data,
                                         form_data[r].material_field.data,
                                         form_data[r].quantity_field.data,
                                         item_time,
                                         item_cost])

            pipe_estimator = estimator.Estimator()
            total_time, total_cost, bom_data = pipe_estimator.man_hours(bom_data=bom_data, rate=hourly_rate)

            return flask.render_template("tools/piping_cost.html",
                                         title="Résultats",
                                         bom=bom_data,
                                         total_time=total_time,
                                         total_cost=total_cost,
                                         hourly_rate=hourly_rate)

        elif form.add_entry_field.data:
            form.add_entry()

        elif form.remove_entries_field.data:
            if not form.remove_entry():
                msg = "Il faut au minimum une ligne."
                flask.flash(msg, "info")

    return flask.render_template("tools/piping_beta.html",
                                 title="Estimateur Beta",
                                 form=form)

@tools.route('/tools', methods=["GET", "POST"])
def piping_estimator():
    form = forms.PipingForm()
    if flask.request.method == 'POST':
        filename = form.file.data.filename
        print(filename)
        file_data = flask.request.files[form.file.name].read()
        image_path = os.path.join(app.config["UPLOAD_PATH"], filename)
        open(image_path, 'wb').write(file_data)
        reader = image_reader.ImageReader()
        bom_content = reader.image_to_text_table(image_path)
        os.remove(image_path)
        return flask.url_for("name", name=bom_content)

    else:
        return flask.render_template("tools/tools.html", title="Estimateur de coûts", form=form)

app/templates/tools/piping_beta.html
{%extends "base.html"%}
{%block title%}{{title}}{%endblock%}
{%block content%}
<div class="container-fluid py-3 w-75">
  <h1>Estimateur de tuyauterie - Beta</h1>
  
  <form action="{{ url_for('tools.piping_beta', n=form.n_rows) }}" method="POST">
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Entrez vos données</legend>
      <div class="form-group">
        {{ form.salary_field.label(class="pe-2") }}
        {{ form.salary_field(width="10") }}
      </div>
      <div class="form-group">
        {% if form.n_rows > 0 %}
        {{ form.hidden_fields }}
        <table class="table table-striped">
          <thead class="thead-light">
            <tr>
              <th scope="col">Item no.</th>
              <th scope="col">{{form.rows[0].item_field.label()}}</th>
              <th scope="col">{{form.rows[0].diameter_field.label()}}</th>
              <th scope="col">{{form.rows[0].schedule_field.label()}}</th>
              <th scope="col">{{form.rows[0].material_field.label()}}</th>
              <th scope="col">{{form.rows[0].quantity_field.label()}}</th>
            </tr>
          </thead>
          <tbody>
            {%for i in range(form.n_rows)%}
            <tr>
              <td scope="row">{{i + 1}}</td>
              <td>{{form.rows[i].item_field}}</td>
              <td>{{form.rows[i].diameter_field}}</td>
              <td>{{form.rows[i].schedule_field}}</td>
              <td>{{form.rows[i].material_field}}</td>
              <td>{{form.rows[i].quantity_field}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      {% endif %}
      </div>
    </fieldset>
    <div class="form-group pt-3">
      {{form.submit_field(class="btn btn-primary")}}
      {{form.add_entry_field(class="btn btn-secondary")}}
      {{form.remove_entries_field(class="btn btn-danger")}}
    </div>
  </form>
</div>
{%endblock%}