app/services_offering/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, FileField, SelectField, FieldList, FormField, BooleanField, FloatField, StringField
from wtforms.validators import DataRequired


class ClientForm(FlaskForm):
    last_name = StringField('Nom', validators=[DataRequired()])
    first_name = StringField('Prénom', validators=[DataRequired()])
    company = StringField('Compagnie', validators=[DataRequired()])
    address = StringField('Adresse', validators=[DataRequired()])
    city = StringField('Ville', default="Sherbrooke", validators=[DataRequired()])
    province = StringField('Province', default="Qc", validators=[DataRequired()])
    zip = StringField('Code Postal', validators=[DataRequired()])

class ProjectDetail(FlaskForm):
    n = 0
    list = FormField(StringField)
    add_button = SubmitField('Ajouter un élément')
    rem_button = SubmitField('Retirer un élément')

    def add_item(self):
        self.n += 1
        self.list.add_entry()

    def rem_item(self):
        if self.n > 0:
            self.n -= 1
            self.list.pop_entry()

class ProjectForm(FlaskForm):
    mandate = StringField('Description du mandat', validators=[DataRequired()])

    mechanical_inclusions = FormField(ProjectDetail, label="Inclusions mécaniques")
    mechanical_exclusions = FormField(ProjectDetail, label="Exclusions mécaniques")
    electrical_inclusions = FormField(ProjectDetail, label="Inclusions électriques")
    electrical_exclusions = FormField(ProjectDetail, label="Exclusions électriques")

class ServicesForm(FlaskForm):
    client_description = FormField(ClientForm, label="Client")
    project_description = FormField(ProjectForm, label="Projet")
    submit = SubmitField("Générer l'offre de services")

app/services_offering/__init__.py
from app import db

class Base(db.Model):
    __bind_key__ = 'clients'
    __abstract__ = True

    id = db.Column(db.Integer, primary_key = True)
    date_created = db.Column(db.DateTime, default=db.func.current_timestamp())
    date_modified = db.Column(db.DateTime, default=db.func.current_timestamp(), onupdate=db.func.current_timestamp())


class Client(Base):
    contact_fname = db.Column("contact_fname", db.String(128), nullable=False)
    contact_name = db.Column("contact_name", db.String(128), nullable=False)
    company_name = db.Column("company_name", db.String(128), nullable=False)
    address = db.Column("address", db.String(256), nullable=False)
    city = db.Column("city", db.String(128), nullable=False)
    province = db.Column("province", db.String(128), nullable=False)
    zip = db.Column("zip", db.String(16), nullable=False)

    def __init__(self, contact_fname, contact_name, company_name, address, city, province, zip):
        self.contact_fname = contact_fname
        self.contact_name = contact_name
        self.company_name = company_name
        self.address = address
        self.city = city
        self.province = province
        self.zip = zip

    def __repr__(self):
        return self.company_name

app/services_offering/controllers.py
import flask
import json
import os

from app import db
from app import app

from app.services_offering import Client
from bin.services_offering.generate_latex_report import ReportBuilder

services_offering = flask.Blueprint('services_offering', __name__)


@services_offering.route('/', methods=["GET", "POST"])
def new_services_offer():
    if flask.request.method == "POST":

        form_data = flask.request.form

        flask.session['offer'] = {}
        flask.session['offer']['project_number'] = form_data['project_number']
        if not flask.session['offer']['project_number']:
            flask.session['offer']['project_number'] = "PXXX"
        flask.session['offer']['client_company'] = form_data['client']
        flask.session['offer']['mandate_type'] = form_data['mandate_type']
        flask.session['offer']['project_name'] = form_data['project_name']


        url = 'services_offering.define_mandate'

        return flask.redirect(flask.url_for(url))
    else:
        clients = Client.query.all()
        offer_types = ['Mécanique du bâtiment', 'Industriel', 'Énergétique', 'Autre']
        available_forms = ['Mécanique du bâtiment', 'Autre']
        return flask.render_template('services_offering/ods.html',
                                     title="Offre de service",
                                     clients=clients,
                                     service_types=offer_types,
                                     available_forms=available_forms)

@services_offering.route('/define_mandate', methods=["GET", "POST"])
def define_mandate():
    if 'client_company' in flask.session['offer']:
        client = Client.query.filter_by(company_name=flask.session['offer']['client_company']).first()
    else:
        msg = "Aucun client n'a été sélectionné. Veuillez sélectionner un client pour continuer."
        flask.flash(flask.Markup(msg), "info")
        return flask.redirect(flask.url_for('services_offering.new_services_offer'))

    if flask.request.method == "POST":
        form_data = flask.request.form

        flask.session['offer']['mandate'] = form_data['role']
        flask.session['offer']['mandate_details'] = []

        # Catégories existantes dans Flask.Session
        details_categories = form_data.getlist('details-category')
        for i in range(len(details_categories)):
            cat = details_categories[i]
            items = form_data.getlist(cat)
            flask.session['offer']['mandate_details'].append([cat, items])

        # Nouvelles catégories ajoutées
        for i in range(15):
            i_str = str(i)
            i_name = i_str + "-name"
            if i_name in form_data:
                cat = form_data[i_name]
                items = form_data.getlist(i_str)
                if len(items) > 0 and not cat == "":
                    flask.session['offer']['mandate_details'].append([cat, items])

        flask.session['offer']['inclusions_defined'] = True
        flask.session.modified = True

        url = "services_offering.price_definition"

        return flask.redirect(flask.url_for(url))
    else:
        if not 'inclusions_defined' in flask.session['offer']:
            mandate_type = flask.session['offer']['mandate_type']

            with open(os.path.join(app.config['BASE_DIR'], 'bin/services_offering/project_specifications.json'),
                      'r', encoding='utf-8') as json_file:
                defaults = json.load(json_file)

                if mandate_type in defaults.keys():
                    flask.session['offer']['mandate_details'] = []
                    for cat in defaults[mandate_type].keys():
                        flask.session['offer']['mandate_details'].append([cat, defaults[mandate_type][cat]])

        return flask.render_template('services_offering/define_mandate.html',
                                     title='Détails du mandat',
                                     client = client)

@services_offering.route('/pricing', methods=["GET", "POST"])
def price_definition():
    if 'client_company' in flask.session['offer']:
        client = Client.query.filter_by(company_name=flask.session['offer']['client_company']).first()
    else:
        msg = "Aucun client n'a été sélectionné. Veuillez sélectionner un client pour commencer."
        flask.flash(flask.Markup(msg), "info")
        return flask.redirect(flask.url_for('services_offering.new_services_offer'))

    if flask.request.method == "POST":
        form_data = flask.request.form

        flask.session['offer']['price_descriptions'] = form_data.getlist('price-description', type=str)
        flask.session['offer']['prices'] = form_data.getlist('price', type=int)
        flask.session['offer']['price_units'] = form_data.getlist('unit', type=str)

        flask.session['offer']['total_price'] = 0
        for i in range(len(flask.session['offer']['prices'])):
            if flask.session['offer']['price_units'][i] == "$":
                flask.session['offer']['total_price'] += flask.session['offer']['prices'][i]
            else:
                flask.session['offer']['varied_price_units'] = True
                break

        flask.session['offer']['prices_defined'] = True

        flask.session.modified = True

        return flask.redirect(flask.url_for('services_offering.review_offer'))
    else:
        units = ['$', '$/hre', '$/km', '$/jr', '$/sem', '$/mois']

        return flask.render_template('services_offering/project_rate.html',
                                     title='Honoraires',
                                     units=units,
                                     client=client)

@services_offering.route('/review')
def review_offer():
    if 'client_company' in flask.session['offer']:
        client = Client.query.filter_by(company_name=flask.session['offer']['client_company']).first()

        return flask.render_template('services_offering/review_offer.html',
                                     title="Offre de services",
                                     client=client)
    else:
        msg = "Aucun client n'a été sélectionné. Veuillez sélectionner un client pour continuer."
        flask.flash(flask.Markup(msg), "info")
        return flask.redirect(flask.url_for('services_offering.new_services_offer'))

@services_offering.route('/generate_pdf')
def generate_pdf():
    useful_keys = ['project_name',
                   'project_number',
                   'mandate',
                   'mandate_details',
                   'prices',
                   'price_descriptions',
                   'price_units',
                   'total_price',
                   'client']


    client = Client.query.filter_by(company_name=flask.session['offer']['client_company']).first()

    data = {}
    data['contact_fname'] = client.contact_fname
    data['contact_name'] = client.contact_name
    data['client_company'] = client.company_name
    data['client_address'] = client.address
    data['client_city'] = client.city
    data['client_province'] = client.province
    data['client_zip'] = client.zip

    for key in flask.session['offer']:
        if key in useful_keys:
            data[key] = flask.session['offer'][key]

    report_builder = ReportBuilder()

    work_dir = os.path.join(app.config['BASE_DIR'], 'bin', 'services_offering', 'latex')
    pdf_file = report_builder.building_mechanics(work_dir, data, app.config['CLIENT_PDF'])

    msg = "<a href='%s' target='_blank'>Ouvrir l'offre de services</a>" % (flask.url_for('services_offering.open_pdf', filename=pdf_file))
    flask.flash(flask.Markup(msg))

    return flask.render_template('services_offering/review_offer.html',
                                 title="Offre de services",
                                 client=client)

@services_offering.route('view_pdf/<filename>')
def open_pdf(filename):
    dir = app.config['CLIENT_PDF']
    safe_path = os.path.join(dir, filename)

    return flask.send_file(safe_path,
                           as_attachment=False,
                           cache_timeout=0)


@services_offering.route('/new_client', methods=["GET", "POST"])
def new_client():
    if flask.request.method == "POST":
        form_data = flask.request.form

        fname = form_data["fname"]
        name = form_data["name"]
        company = form_data["company"]
        address = form_data["address"]
        city = form_data["city"]
        province = form_data["province"]
        zip = form_data["zip"]

        client = Client(fname, name, company, address, city, province, zip)
        db.session.add(client)
        db.session.commit()

        return flask.redirect(flask.url_for('services_offering.new_services_offer'))

    return flask.render_template('services_offering/new_client.html')

app/templates/services_offering/building_mechanic_form.html
{% extends "base.html" %}
{% block scripts %}{% endblock %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<div class="container-fluid w-100 p-5">
  <p>
    <b>{{ client.contact_fname + " " + client.contact_name }}</b><br>
    {{ client.company_name }}<br>
    {{ client.address }}<br>
    {{ ", ".join([client.city, client.province, client.zip]) }}<br>
  </p>
  <h5>Offre de services: {{ session['offer']['project_name'] }}</h5>
  <form id="mandate-form" class="form-inline" method="POST">
    <fieldset class="form-group">
      <!-- Mandate description -->
      <div class="form-group mt-2">
        <label for="role">Description du mandat</label>
        <textarea id="role" name="role" class="form-control" rows="4" required="Required">Albert Groupe conseil sera responsable de</textarea>
      </div>
      <br>
      
      <!-- Mechanical section -->
      <button class="btn btn-secondary mt-2" type="button" onclick="toggleSection('mec-details')">Détailler la partie mécaniques</button>
      <div class="mt-2 form-group" id="mec-details" style="display:None">
        <h5><u>Inclusions Mécaniques</u></h5>
        <button class="btn btn-success" type="button" onclick="addElement('mec-inclusions-table', 'mec-inc')">Ajouter une inclusion</button>
        <button class="btn btn-danger" type="button" onclick="remSelectedElements('mec-inclusions-table')">Supprimer les inclusions sélectionnées</button>
        <table class="table" id="mec-inclusions-table">
          {% for e in session['offer']['mec_inc'] %}
          <tr>
            <td style="width:2%"><input type="checkbox" class="checkbox"></td>
            <td><input type="text" class="form-control" name="mec-inc" value="{{ e }}"></td>
          </tr>
          {% endfor %}
        </table>
        
        <h5><u>Exclusions Mécaniques</u></h5>
        <button class="btn btn-success" type="button" onclick="addElement('mec-exclusions-table', 'mec-exc')">Ajouter une exclusion</button>
        <button class="btn btn-danger" type="button" onclick="remSelectedElements('mec-exclusions-table')">Supprimer les exclusions sélectionnées</button>
        <table class="table" id="mec-exclusions-table">
          {% for e in session['offer']['mec_exc'] %}
          <tr>
            <td style="width:2%"><input type="checkbox" class="checkbox"></td>
            <td><input type="text" class="form-control" name="mec-exc" value="{{ e }}"></td>
          </tr>
          {% endfor %}
        </table>
      </div>
      <br>
      
      <!-- Electrical Section -->
      <button class="btn btn-secondary mt-2" type="button" onclick="toggleSection('elec-details')">Détailler la partie électrique</button>
      <div class="mt-2 form-group" id="elec-details" style="display:None">
        <h5><u>Inclusions Électriques</u></h5>
        <button class="btn btn-success" type="button" onclick="addElement('elec-inclusions-table', 'elec-inc')">Ajouter une inclusion</button>
        <button class="btn btn-danger" type="button" onclick="remSelectedElements('elec-inclusions-table')">Supprimer les inclusions sélectionnées</button>
        <table class="table mt-1" id="elec-inclusions-table">
          {% for e in session['offer']['elec_inc'] %}
          <tr>
            <td style="width:2%"><input type="checkbox" class="checkbox"></td>
            <td><input type="text" class="form-control" name="elec-inc" value="{{ e }}"></td>
          </tr>
          {% endfor %}
        </table>
        
        <h5><u>Exclusions Électriques</u></h5>
        <button class="btn btn-success" type="button" onclick="addElement('elec-exclusions-table', 'elec-exc')">Ajouter une exclusion</button>
        <button class="btn btn-danger" type="button" onclick="remSelectedElements('elec-exclusions-table')">Supprimer les exclusions sélectionnées</button>
        <table class="table" id="elec-exclusions-table">
          {% for e in session['offer']['elec_exc'] %}
          <tr>
            <td style="width:2%"><input type="checkbox" class="checkbox"></td>
            <td><input type="text" class="form-control" name="elec-exc" value="{{ e }}"></td>
          </tr>
          {% endfor %}
        </table>
      </div>
      
      <!-- Script -->
      <script type="text/javascript">
        function toggleSection(id) {
          var element = document.getElementById(id);
          if (element.style.display == 'none') {
            element.style.display = 'block';
          } else {
            element.style.display = 'none';
          }
        }
        
        function addElement(table_id, element_name) {
          var table = document.getElementById(table_id);
          var new_row = table.insertRow(-1);
          new_row.innerHTML = `<td><input type="checkbox" class="checkbox"></td>\
                               <td><input type="text" class="form-control" name="$(element_name)"></td>`;
        }
        
        function remSelectedElements(table_id) {
          var table = document.getElementById(table_id);
          var rows = table.getElementsByTagName("tr");
          var boxes = table.getElementsByClassName("checkbox");
          
          for (var i=rows.length-1; i>=0; i--) {
            if (boxes[i].checked) {
              rows[i].parentNode.removeChild(rows[i]);
            }
          }
        }
      </script>
      
      
      <div class="form-group mt-2">
        <button class="btn btn-primary" type="submit" value="Submit">Suivant</button>
        <a href="{{url_for('services_offering.new_services_offer')}}">
          <button class="btn btn-danger" type="button">Annuler</button>
        </a>
      </div>
    </fieldset>
  </form>
</div>
{% endblock %}

app/templates/services_offering/new_client.html
{% extends "base.html" %}
{% block scripts %}{% endblock %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<div class="container-fluid w-75 p-5">
  <h3 class="border-bottom mb-4">Nouveau client</h3>
  <form id="new-client-form" class="form" method="POST" action="{{url_for('services_offering.new_client')}}">
    <fieldset class="form-group">
      <legend class="pt-1">Personne Contact</legend>
      <label for="fname" class="form-field-label">Prénom</label>
      <input type="text" id="fname" name="fname" class="form-control" required="Required">
      <label for="name" class="form-control-label">Nom</label>
      <input type="text" id="name" name="name" class="form-control" required="Required">
      
      <legend class="pt-2">Informations sur la compagnie</legend>
      <label for="company" class="form-control-label">Compagnie</label>
      <input type="text" id="company" name="company" class="form-control" required="Required">
      <label for="address" class="form-control-label">Adresse</label>
      <input type="text" id="address" name="address" class="form-control" required="Required">
      <label for="city" class="form-control-label">Ville</label>
      <input type="text" id="city" name="city" class="form-control" required="Required">
      <label for="province" class="form-control-label">Province</label>
      <input type="text" id="province" name="province" class="form-control" required="Required" value="Québec">
      <label for="zip" class="form-control-label">Code Postal</label>
      <input type="text" id="zip" name="zip" class="form-control" required="Required">
      
      <button class="btn btn-primary mt-2" type="submit" value="Submit">Créer un nouveau client</button>
      <a href="{{url_for('services_offering.new_services_offer')}}">
        <button class="btn btn-danger mt-2 mb-auto" type="button">Annuler</button>
      </a>
    </fieldset>
  </form>
</div>
{% endblock %}

app/templates/services_offering/ods.html
{% extends "base.html" %}
{% block scripts %}{% endblock %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="container-fluid w-75 p-5">
  <h3 class="border-bottom mb-4">Nouvelle offre de servies</h3>
  <form class="form-inline" method="POST" id="services_form" action="">
    <!-- Project Number -->
    <h5 class="pt-2">Numéro de projet (optionnel)</h5>
    <div class="input-group">
      <input type="text" id="project-number" name="project_number" class="form-control" placeholder="PXXXX">
    </div>
    
    <!-- Section Client -->
    <h5 class="pt-2">Client</h5>
    <div class="input-group">
      <select class="form-select" name="client" id="existing-client" required="required">
        <option selected disabled hidden>Choisir ...</option>
        {% for client in clients %}
        <option value="{{client}}">{{client}}</option>
        {% endfor %}
      </select>
      <a href="{{url_for('services_offering.new_client')}}"><button class="btn btn-success" type="button">Nouveau client</button></a>
    </div>
    
    <!-- Object section -->
    <h5 class="pt-2">Titre tu projet</h5>
    <div class="input-group">
      <input type="text" id="project-name" name="project_name" class="form-control" required="required">
    </div>
    
    <!--- Section Services -->
    <h5 class="pt-2">Services</h5>
    <div class="input-group">
      <select class="form-select" name="mandate_type" onchange="defineMandate({{ available_forms }})" id="mandate-type">
        <option selected disabled hidden>Choisir ...</option>
        {% for type in service_types %}
        <option value="{{type}}">{{type}}</option>
        {% endfor %}
      </select>
    </div>
    <div class="py-2" id="next-step" style="display:none">
    </div>
    <script type="text/javascript">
      function defineMandate(available_forms) {
        var mandateDefinitionDiv = document.getElementById("next-step");
        var mandate = document.getElementById("mandate-type").value;
        
        if (available_forms.includes(mandate)) {
          mandateDefinitionDiv.innerHTML = '<button form="services_form" type="submit" value="Submit" class="btn btn-primary">Suivant</button>';
        } else {
          mandateDefinitionDiv.innerHTML = "<b>Option à venir. Utiliser le fichier Word pour l'instant</b>";
        }
        mandateDefinitionDiv.style.display = 'Block';
      }
    </script>
  </form>
</div>
{% endblock %}

app/templates/services_offering/project_rate.html
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<div class="container-fluid w-100 p-5">
  <div class="card card-body">
    <p>
      <b>{{ client.contact_fname + " " + client.contact_name }}</b><br>
      {{ client.company_name }}<br>
      {{ client.address }}<br>
      {{ ", ".join([client.city, client.province, client.zip]) }}<br>
    </p>
    
    <h5>Offre de services: {{ session['offer']['project_name'] }}</h5>
    <b>Description du mandat</b>
    <p>{{ session['offer']['mandate'] }}</p>
    
    <!-- Détails du mandat -->
    {% for i in range(session['offer']['mandate_details']|length) %}
      <b>{{ session['offer']['mandate_details'][i][0] }}</b>
      <ul>
        {% for i in session['offer']['mandate_details'][i][1] %}
        <li>{{ i }}</li>
        {% endfor %}
      </ul>
    {% endfor %}
  </div>
  <div class="w-75 container-fluid p-3">
    <h5>Honoraires</h5>
    <form id="mandate-form" class="form-inline" method="POST">
      <fieldset class="form-group">
        <button class="btn btn-success" type="button" onclick="addElement('price-table', 'price')">Ajouter une catégorie</button>
        <button class="btn btn-danger" type="button" onclick="remSelectedElements('price-table')">Supprimer les catégories sélectionnées</button>
        <table class="table" id="price-table">
          {% for i in range(session['offer']['prices']|length) %}
          <tr>
            <td><input type="checkbox" class="checkbox"></td>
            <td><input type="text" class="form-control" name="price-description" value="{{ session['offer']['price_descriptions'][i]}} "></td>
            <td>
              <div class="input-group">
                <div class="input-group-prepend">
                  <select class="form-select" name="unit" required="required">
                    <option selected value="{{ session['offer']['price_units'][i] }}">
                      {{ session['offer']['price_units'][i] }}
                    </option>
                    {% for unit in units %}
                    <option value="{{unit}}">{{unit}}</option>
                    {% endfor %}
                  </select>
                </div>
                <input type="number" class="form-control" name="price" value="{{ session['offer']['prices'][i] }}" required>
              </div>
            </td>
          </tr>
          {% endfor %}
          <tr>
            <td><input type="checkbox" class="checkbox"></td>
            <td><input type="text" class="form-control" name="price-description" placeholder="Ingénierie mécanique"></td>
            <td>
              <div class="input-group">
                <div class="input-group-prepend">
                  <select class="form-select" name="unit" required="required">
                    {% for unit in units %}
                    <option value="{{unit}}">{{unit}}</option>
                    {% endfor %}
                  </select>
                </div>
                <input type="number" class="form-control" name="price" placeholder="Entrer le montant" required>
              </div>
            </td>
          </tr>
        </table>
        
        <script type="text/javascript">
          function addElement(table_id, element_name) {
            var table = document.getElementById(table_id);
            var new_row = table.insertRow(-1);
            new_row.innerHTML = `<td><input type="checkbox" class="checkbox"></td>\
                                  <td><input type="text" class="form-control" name="price-description" placeholder="Entrer la catégorie"></td>\
                                  <td>\
                                    <div class="input-group">\
                                      <div class="input-group-prepend">\
                                        <select class="form-select" name="unit" required="required">\
                                          {% for unit in units %}\
                                          <option value="{{unit}}">{{unit}}</option>\
                                          {% endfor %}\
                                        </select>\
                                      </div>\
                                      <input type="number" class="form-control" name="price" placeholder="Entrer le montant" required>\
                                    </div>\
                                  </td>`;
          }
          
          function remSelectedElements(table_id) {
            var table = document.getElementById(table_id);
            var rows = table.getElementsByTagName("tr");
            var boxes = table.getElementsByClassName("checkbox");
            
            for (var i=rows.length-1; i>=0; i--) {
              if (boxes[i].checked) {
                rows[i].parentNode.removeChild(rows[i]);
              }
            }
          }
        </script>
        
        <div class="form-group mt-2">
          <button class="btn btn-primary" type="submit" value="Submit">Suivant</button>
          <a href="{{url_for('services_offering.new_services_offer')}}">
            <button class="btn btn-danger" type="button">Annuler</button>
          </a>
        </div>
      </fieldset>
    </form>
  </div>
</div>
{% endblock %}

app/templates/services_offering/review_offer.html
{% extends "base.html" %}
{% block scripts %}{% endblock %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<div class="container-fluid w-75">
  <div class="card card-body mx-auto px-5 py-7" style="width:8.5in" id="print-area">
    <!-- DATE -->
    <div>
      <p id="date">Sherbrooke, le </p>
      <script type="text/javascript">
        let months = ["", "janvier", "février", "mars", "avril", "mai", "juin", "juillet", "août", "septembre", "novembre", "décembre"];
        let [year, month, date] = new Date().toLocaleDateString("fr-CA").split('-');
        //let today = new Date().toLocaleDateString("fr-CA").split('-');
        
        document.getElementById("date").innerHTML += `${date} ${months[Number(month)]} ${year}`;
      </script>
    </div>
    
    <!-- ENTÊTE -->
    <div>
      <p>
        <b>{{ client.contact_fname + " " + client.contact_name }}</b><br>
        {{ client.company_name }}<br>
        {{ client.address }}<br>
        {{ ", ".join([client.city, client.province, client.zip]) }}<br>
      </p>
      <p><b>Sujet: Offre de services {{ session['offer']['project_name']}}</b></p>
      <p>Bonjour {{ client.contact_fname }},</p>
      <p>Voici notre offre de service pour la réalisation du projet: {{ session['offer']['project_name']}}.</p>
    </div>
    
    <!-- DESCRIPTION DU MANDAT -->
    <div>
      <b>Description du mandat</b>
      <p>{{ session['offer']['mandate'] }}</p>
    </div>
    
    <!-- Définition du mandat -->
    <div>
      {% for i in range(session['offer']['mandate_details']|length) %}
      <b>{{ session['offer']['mandate_details'][i][0] }}</b>
      <ul>
        {% for i in session['offer']['mandate_details'][i][1] %}
        <li>{{ i }}</li>
        {% endfor %}
      </ul>
        {% endfor %}
    </div>
    
    <!-- HONORAIRES -->
    <div>
      <b>HONORAIRES*</b>
      <div class="container-fluid w-75 mx-auto justify-content-center">
        <table class="table">
          {% for i in range(session['offer']['prices']|length) %}
          <tr>
            <td>{{ session['offer']['price_descriptions'][i] }}</td>
            <td>{{ session['offer']['prices'][i] }} {{ session['offer']['price_units'][i] }}</td>
          </tr>
          {% endfor %}
          {% if not session['offer']['varied_price_units'] %}
          <tr>
            <th scope="row" class="sticky-end">TOTAL</th>
            <td><b>{{ session['offer']['total_price'] }} $</b></td>
          </tr>
          {% endif %}
        </table>
        <small>* Ces taux excluent les taxes applicables</small>
      </div>
    </div>
    
    <!-- DÉLAIS -->
    <div>
      <b>Délais</b>
      <p class="mb-3">Délais à déterminer avec le client.</p>
    </div>
  
    <!-- TERMES ET CONDITIONS -->
    <div>
      <b>Termes et conditions</b>
      <ul>
        <li>Facturation mensuelle progressive basée sur l'avancement du mandat, payable 30 jours après la réception de la facture</li>
        <li>Cette offre est valide pour une période de 30 jours</li>
      </ul>
    </div>
    
    <!-- SIGNATURES -->
    <div>
      <p>Sur réception de cotre approbation de l'offre de services, par la signature de la présente, nous débuterons le mandat.</p>
      <p>En espérant le tout conforme à vos attentes.</p>
      <p>Cordialement,</p>
      
      <div class="container">
        <div class="row">
          <div class="col-6">
            <img class="w-50" src="{{url_for('static', filename='/images/local/signature_sam.png')}}">
          </div>
          <div class="col-6">
          </div>
        </div>
        <div class="row">
          <div class="col-6">
            <hr class="w-75">
            <p>
              Préparé par:<br>
              Samuel Leblanc-Robert, ing.<br>
              Albert Groupe Conseil inc.
            </p>
          </div>
          <div class="col-6">
            <hr class="w-75">
            <p>
              Approuvé par:<br>
              {{ client.contact_fname }} {{ client.contact_name }}<br>
              {{ client.company_name }}
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  <!-- IMPRESSION -->
  <div class="pt-3">
    <a type="button" class="btn btn-primary" href={{url_for('services_offering.generate_pdf')}}>Créer le PDF</a>
  </div>
</div>
{% endblock %}