app/user_profile/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo

class EditProfileFrom(FlaskForm):
    username = StringField('Nom d''utilisateur', validators=[Length(min=2, max=20)])
    email = StringField('Email', validators=[Email()])
    old_password = PasswordField('Mot de passe actuel', validators=[DataRequired()])
    new_password = PasswordField('Nouveau mot de passe',
                                 validators=[EqualTo('confirm_new_password')])
    confirm_new_password = PasswordField('Confirmer nouveau mot de passe',
                                         validators=[EqualTo('new_password')])
    submit = SubmitField('Enregistrer')

class DeleteProfileForm(FlaskForm):
    i_understand = BooleanField("J'ai bien compris.", validators=[DataRequired()])
    submit = SubmitField('Supprimer définitivement mon compte')

app/user_profile/controllers.py
import flask
from app import db
from app.authentification import User, hash_string
from app.user_profile import forms

user_profile = flask.Blueprint('user_profile', __name__)

@user_profile.route('/')
def profile_page():
    if 'user' in flask.session:
        username = flask.session['user']
        user = User.query.filter_by(name=username).first()

        return flask.render_template("user_profile/profile_page.html", title=user.name, user=user)
    else:
        msg = f"Vous n'êtes pas connecté. <a href={flask.url_for('auth.login')}>Se connecter?</a>"
        url = 'main.home'

        flask.flash(flask.Markup(msg), 'info')
        return flask.redirect(flask.url_for(url))

@user_profile.route("/edit", methods=["GET", "POST"])
def edit_profile():
    if 'user' in flask.session:
        username = flask.session['user']
        user = User.query.filter_by(name=username).first()
        form = forms.EditProfileFrom()
        if flask.request.method == "POST":
            update_db = False
            msg = None
            url = flask.url_for('user_profile.edit_profile')
            if hash_string(flask.request.form['old_password'], user.salt)[0] == user.password:
                new_username = flask.request.form['username']
                new_email = flask.request.form['email']
                new_password = flask.request.form['new_password']
                confirm_new_password = flask.request.form['confirm_new_password']

                if not new_username == user.name:
                    user.name = new_username
                    update_db = True

                if not new_email == user.email:
                    user.email = new_email
                    update_db = True

                if new_password:
                    if new_password == confirm_new_password:
                        user.password, user.salt = hash_string(flask.request.form['new_password'])
                        update_db = True
                    else:
                        msg = "Les nouveaux mots de passe ne sont pas identiques. "
                        msg += "Aucune donnée enregistré."
                        update_db = False


                if update_db:
                    db.session.commit()
                    msg = "Vos données ont été enregistré avec succès."
                    url = flask.url_for('user_profile.profile_page')

                    flask.session['user'] = new_username
                else:
                    if not msg:
                        msg = "Aucune modification apportée. Cliquez sur annuler pour revenir à votre profil."

            else:
                msg = "Votre mot de passe actuel est invalide. Aucun changement apporté à votre compte."

            if msg:
                flask.flash(msg, "info")
            return flask.redirect(url)

        else:
            return flask.render_template("user_profile/edit_profile.html", form=form, title=user.name, user=user)

    else:
        msg = f"Vous n'êtes pas connecté. <a href={flask.url_for('auth.login')}>Se connecter?</a>"
        url = 'main.home'

        flask.flash(flask.Markup(msg), 'info')
        return flask.redirect(flask.url_for(url))

@user_profile.route('/delete_account', methods=["GET", "POST"])
def delete_account():
    if 'user' in flask.session:
        form = forms.DeleteProfileForm()
        if flask.request.method == "POST":
            user = User.query.filter_by(name=flask.session["user"]).first()
            db.session.delete(user)
            db.session.commit()

            flask.session.pop('user', None)
            msg = "Votre compte a été supprimé avec succès"
            url = "main.home"
        else:
            return flask.render_template('user_profile/delete_account.html', title="Supprimer mon compte", form=form)
    else:
        msg = f"Vous devez <a href={flask.url_for('auth.login')}>vous connecter</a> afin de supprimer votre compte."
        url = "main.home"

    if msg:
        flask.flash(flask.Markup(msg), 'info')
    return flask.redirect(flask.url_for(url))

app/templates/user_profile/delete_account.html
{% extends "base.html" %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class="container-fluid w-75 py-3" style="max-width:750px">
  <form method="POST">
    <fieldset class="form-group text-center">
      <legend class="border-bottom mb-4">Supprimer définitivement mon compte</legend>
      <p>Cette action est irréversible. Toutes vos données donées d'utilisateur seront perdues et supprimées définitivement.</p>
      <div class="form-group pb-3">
        {{form.i_understand(class="form-checkbox")}}
        {{form.i_understand.label(class="form-checkbox-label")}}
      </div>
      <p>Pour confirmer la suppression de votre compte appiyez sur le bouton ci-dessous.</p>
      <div class="form-group pb-3">
        {{ form.submit(class="btn btn-danger") }}
      </div>
    </fieldset>
  </form>
</div>
{% endblock %}

app/templates/user_profile/edit_profile.html
{% extends "base.html" %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class="container-fluid py-3 w-75" style="max-width:750px">
  <form method="POST" action="">
    <table class="table">
      <thead class="thead">
        <tr class="text-align-center">
          <th scope="row" colspan="2">
            <h2 class="text-uppercase"><b>Modifier mon profil</b></h2>
          </th>
        </tr>
      </thead>
      <tr class="align-middle">
        <th scope="row">{{ form.username.label(class="form-control-label") }}</th>
        <td>{{ form.username(class="form-control", value=user.name) }}</td>
      </tr>
      <tr class="align-middle">
        <th scope="row">{{ form.email.label(class="form-control-label") }}</th>
        <td>{{ form.email(class="form-control", value=user.email) }}</td>
      </tr>
      <tr class="align-middle">
        <th scope="row">{{ form.old_password.label(class="form-control-label") }}</th>
        <td>{{ form.old_password(class="form-control") }}</td>
      </tr>
      <tr class="align-middle">
        <th scope="row">{{ form.new_password.label(class="form-control-label") }}</th>
        <td>{{ form.new_password(class="form-control") }}</td>
      </tr>
      <tr class="align-middle">
        <th scope="row">{{ form.confirm_new_password.label(class="form-control-label") }}</th>
        <td>{{ form.confirm_new_password(class="form-control") }}</td>
      </tr>
    </table>
    <div class="container-fluid text-end">
        {{ form.submit(class="btn btn-primary") }}
        <a class="btn btn-secondary" href={{url_for('user_profile.profile_page')}}>Annuler</a>
     </div>
  </form>
  <div class="w-100 text-center mt-5">
    <small class="text-muted">
      <a class="btn btn-small  btn-danger" href={{url_for('user_profile.delete_account')}}>Supprimer mon compte</a>
    </small>
  </div>
</div>
{% endblock %}

app/templates/user_profile/profile_page.html
{% extends "base.html" %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class="container-fluid py-3 w-75" style="max-width:750px">
  <table class="table">
    <thead class="thead">
      <tr class="text-align-center">
        <th scope="row">
          <h2 class="text-uppercase"><b>Mon profil</b></h2>
        </th>
        <td class="text-end">
          <form action={{url_for('user_profile.edit_profile')}}>
            <button class="btn btn-secondary">Modifier</button>
          </form>
        </td>
      </tr>
    </thead>
    <tr class="align-middle">
      <th scope="row">Nom d'utilisateur:</th>
      <td>{{ user.name }}</td>
    </tr>
    <tr class="align-middle">
      <th scope="row">Addresse courriel:</th>
      <td>{{ user.email }}</td>
    </tr>
    <tr class="align-middle">
      <th scope="row">Mot de passe:</th>
      <td>************</td>
    </tr>
  </table>
</div>
{% endblock %}