app/authentification/controllers.py
import flask

from app import db
from app import mail_service

from app.authentification import forms
from app.authentification import User
from app.authentification import hash_string, get_random_string


auth = flask.Blueprint('auth', __name__)

@auth.route('/register', methods=["GET", "POST"])
def register():
    if flask.request.method == "POST":
        email = flask.request.form['email']
        found_user = User.query.filter_by(email=email).first()
        if found_user:
            msg = f'Un compte existe déjà avec ce email. <a href={flask.url_for("auth.login")}>Se connecter?</a>'
            url = "auth.register"
        else:
            username = flask.request.form['username']
            password, salt = hash_string(flask.request.form['password'])
            flask.session['user'] = username

            usr = User(username, email, password, salt)
            db.session.add(usr)
            db.session.commit()

            msg = f"Connecté en tant que {username}"
            url = "main.home"


        flask.flash(flask.Markup(msg), "info")

        return flask.redirect(flask.url_for(url))
    else:
        form = forms.RegistrationForm()
        return flask.render_template("auth/register.html", title="S'inscrire", form=form)

@auth.route('/login', methods=["GET", "POST"])
def login():
    if flask.request.method == "POST":
        email = flask.request.form['email']
        found_user = User.query.filter_by(email=email).first()
        if found_user:
            password, _ = hash_string(flask.request.form['password'], found_user.salt)
            if found_user.password == password:
                username = found_user.name
                flask.session["user"] = username
                if 'keep_me_signed' in flask.request.form:
                    flask.session.permanent = True

                msg = f"Connecté en tant que {username}"
                url = "main.home"

            else:
                msg = "Mot de passe invalide"
                url = "auth.login"

        else:
            msg = f'Aucun utilisateur correspond à cet email. <a href={flask.url_for("auth.register")}>S''inscrire?</a>'
            url = "auth.login"

        flask.flash(flask.Markup(msg), "info")
        return flask.redirect(flask.url_for(url))
    else:
        form = forms.LoginForm()
        return flask.render_template("auth/login.html", title="Connection", form=form)

@auth.route('/forgot_password', methods=["GET", "POST"])
def forgot_password():
    if flask.request.method == "POST":
        email = flask.request.form['email']
        found_user = User.query.filter_by(email=email).first()
        if found_user:
            username = found_user.name

            tmp_link = get_random_string(16)
            found_user.tmp_link = tmp_link
            db.session.commit()

            msg_link = "www.albert-toolbox.com" + flask.url_for('auth.reset_password', username=username, tmp_link=tmp_link)
            print(msg_link)

            if mail_service.reset_password(email, username, msg_link):
                msg = f"Un lien pour réinitialiser votre mot de passe a été envoyé à {email}. "
                url = "main.home"
            else:
                msg = "Une erreur est survenue. Veuillez réessayer plus tard."
                url = "auth.login"
        else:
            msg = f'Aucun utilisateur correspond à cet email. <a href={flask.url_for("auth.register")}>S''inscrire?</a>'
            url = "auth.forgot_password"

        flask.flash(flask.Markup(msg), "info")
        return flask.redirect(flask.url_for(url))
    else:
        form = forms.ForgotPasswordForm()
        return flask.render_template("auth/forgot_password.html", title="Mot de passe oublié", form=form)

@auth.route('/<username>/<tmp_link>', methods=["GET", "POST"])
def reset_password(username, tmp_link):
    found_user = User.query.filter_by(name=username).first()
    if found_user:
        if found_user.tmp_link == tmp_link:
            if flask.request.method == "POST":
                password, salt = hash_string(flask.request.form['password'])
                found_user.password = password
                found_user.salt = salt
                found_user.tmp_link = ""

                db.session.commit()

                flask.session['user'] = found_user.name
                msg = "Mot de passe changé avec succès!"
                url = "main.home"
            else:
                form = forms.ResetPasswordForm()
                return flask.render_template("auth/reset_password.html", title="Changer de mot de passe", form=form)
        else:
            msg = "Le lien utilié est expiré ou invalide. Veuillez valider que vous avez bien utilisé le plus récent ou "
            msg += f'<a href={flask.url_for("auth.forgot_password")}>envoyer à nouveau</a>.'
            url = "main.home"

        flask.flash(flask.Markup(msg), "info")
        return flask.redirect(flask.url_for(url))


@auth.route('/logout')
def logout():
    if "user" in flask.session:
        flask.session.pop("user", None)
        flask.session.permanent = False
        flask.flash("Déconnecté avec succès", "info")

    return flask.redirect(flask.url_for("main.home"))

app/building_mec/controllers.py
import flask

from app.building_mec import forms
#from bin import estimator

building_tools = flask.Blueprint('building_tools', __name__)


@building_tools.route('/building_tools/', defaults={"n": 2}, methods=["GET", "POST"])
@building_tools.route('/building_tools/<n>', methods=["GET", "POST"])
def building_description(n):
    form = forms.BetaHVACForm()
    for _ in range(n):
        form.add_entry()

    return flask.render_template("building_mec/building_description.html",
                                 title="Mécanique du bâtiment",
                                 form=form)

app/main/controllers.py
import flask
import os
import markdown as md

from app import app

main = flask.Blueprint('main', __name__, )

@main.route('/')
def home():
    content_dir = "app/static/content/index"
    abs_dir = os.path.join(app.config['BASE_DIR'], content_dir)
    titles, contents = get_content(abs_dir)

    return flask.render_template("main/content_page.html", title="Accueil", titles=titles, content=contents)

@main.route('/tools')
def show_tools():
    content_dir = "app/static/content/our_tools"
    abs_dir = os.path.join(app.config['BASE_DIR'], content_dir)
    titles, contents = get_content(abs_dir)

    return flask.render_template("main/content_page.html", title="Nos Outils", titles=titles, content=contents)

def get_content(dir):
    titles = []
    contents = []

    files = [f for f in os.listdir(dir) if os.path.isfile(os.path.join(dir, f))]

    for file in files:
        file_title, file_content = read_article(os.path.join(dir, file))
        contents.append(file_content)
        titles.append(file_title)

    return titles, contents

def read_article(file):
    line_count = 0
    title = ""
    content = ""
    with open(file, 'r', encoding='utf-8') as f:
        for r in f:
            if line_count == 0:
                title += r
                line_count += 1
            else:
                content += r

    md_title = md.markdown(title)
    md_content = md.markdown(content)
    return md_title, md_content

app/piping_estimator/controllers.py
import flask

from app.piping_estimator import forms
from bin import estimator

tools = flask.Blueprint('piping_estimator', __name__)


@tools.route('/piping_beta/', defaults={"n": 2}, methods=["GET", "POST"])
@tools.route('/piping_beta/<n>', methods=["GET", "POST"])
def piping_beta(n):
    n = int(n)
    form = forms.BetaPipingForm()
    for _ in range(n):
        form.add_entry()

    if flask.request.method == "POST":
        if form.submit_field.data:
            form_data = form.rows
            n_rows = len(form_data)

            hourly_rate = form.salary_field.data
            bom_data = []
            item_time = 0
            item_cost = 0
            for r in range(0, n_rows):
                if form_data[r].quantity_field.data:
                    row_qty = form_data[r].quantity_field.data
                    if not row_qty in [float("inf"), float("-inf")]:
                        bom_data.append([r+1,
                                         form_data[r].item_field.data,
                                         form_data[r].diameter_field.data,
                                         form_data[r].schedule_field.data,
                                         form_data[r].material_field.data,
                                         form_data[r].quantity_field.data,
                                         item_time,
                                         item_cost])

            pipe_estimator = estimator.Estimator()
            total_time, total_cost, bom_data = pipe_estimator.man_hours(bom_data=bom_data, rate=hourly_rate)

            return flask.render_template("piping_estimator/piping_cost.html",
                                         title="Résultats",
                                         bom=bom_data,
                                         total_time=total_time,
                                         total_cost=total_cost,
                                         hourly_rate=hourly_rate)

        elif form.add_entry_field.data:
            form.add_entry(copy=True)

        elif form.remove_entries_field.data:
            if not form.remove_entry():
                msg = "Il faut au minimum une ligne."
                flask.flash(msg, "info")

    return flask.render_template("piping_estimator/piping_beta.html",
                                 title="Estimateur Beta",
                                 form=form)

app/templates/base.html
<!DOCTYPE html>

<html lang="fr">
<head>
  <meta charset="UTF-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
        crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='style.css')}}">
  <link rel="shortcut icon" href="{{url_for('static', filename='images/icon.ico')}}" type="image/x-icon">
  
  <title>{% block title %}{% endblock %}</title>
</head>

<body class="d-flex flex-column min-vh-100 w-100">
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href={{url_for("main.home")}}>
        <img src={{url_for('static', filename='images/logo.png')}} alt="Les outils Albert" width="250px">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
              data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup"
              aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup" style="font-size:1.4rem;">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href={{url_for('main.show_tools')}}>
            Nos outils
          </a>
          <a class="nav-item nav-link active" href={{url_for('building_tools.building_description')}}>
            Mécanique du bâtiment 
          </a>
          <a class="nav-item nav-link active" href={{url_for('piping_estimator.piping_beta')}}>
            Tuyauterie industrielle
          </a>
        </div>
        <span class="navbar-nav ms-auto">
          {% if "user" in session %}
            <a class="nav-link active position-sticky-end" href={{url_for("user_profile.profile_page")}}>
              {{session["user"]}}
            </a>
            <a class="nav-link position-sticky-end" href={{url_for("auth.logout")}}>
              Déconnexion
            </a>
          {% else %}
            <a class="nav-link position-sticky-end" href={{url_for("auth.register")}}>
              S'enregistrer
            </a>
            <a class="nav-link position-sticky-end" href={{url_for("auth.login")}}>
              Connexion
            </a>
          {% endif %}
        </span>
      </div>
    </div>
  </nav>
  <!-- Messages / Alerts -->
  {% with messages = get_flashed_messages() %}
    {% if messages %}
      {% for msg in messages %}
        <div class="alert alert-primary" role="alert">{{msg}}</div>
      {% endfor %}
    {% endif %}
  {% endwith %}
  
  <!-- Page Content -->
  <div class="w-100 my-3">
    {% block content %}{% endblock %}
  </div>
  
  <!-- Footer -->
  <footer class="bg-dark text-center text-lg-start mt-auto">
    <div class="container p-4 text-light">
      <div class="row ">
        <div class="col-lg-4 col-md-12 mb-4 mb-md-0">
          <h4 class="text-uppercase">Albert Toolbox. Une division de</h4>
          <div class="text-center pt-1">
            <a href="http://www.albertconseil.com/">
              <img class="img-center"
                   src={{url_for('static', filename='images/albert_logo.png')}}
                   alt="Albert Groupe Conseil" width="250px">
            </a>
          </div>
          
        </div>
        <div class="col-lg-4 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">navigation</h5>
  
          <ul class="list-unstyled mb-0">
            <li>
              <a href={{url_for("main.home")}} class="text-light">Accueil</a>
            </li>
            <li>
              <a href={{url_for("main.show_tools")}} class="text-light">Nos Outils</a>
            </li>
            <li>
              <a href={{url_for("piping_estimator.piping_beta")}} class="text-light">Estimateur de tuyauterie</a>
            </li>
          </ul>
        </div>
        <div class="col-lg-4 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase mb-0">Nous joindre</h5>
  
          <ul class="list-unstyled">
            <li>
              <a target="_blank" href="http://www.albertconseil.com/" class="text-light">albertconseil.com</a>
            </li>
            <li>
              <a href="#" class="text-light">Contacts</a>
            </li>
            <li>
              <a href="mailto:gcharland@albertconseil.com?subject=Albert%20Toolbox%20-%20-Demande%20d'information"
                 class="text-light">Courriel</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="text-center p-3 text-light" style="background-color: rgba(0, 0, 0, 0.2)">
      © 2021 Copyright:
      <a class="text-light" href="mailto:g.charland1@protonmail.com">Gabriel Charland</a>
    </div>
  </footer>
  
  <!-- Scripts -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"
          integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU"
          crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js"
          integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj"
          crossorigin="anonymous"></script>
</body>

</html>

app/templates/index.html
{%extends "base.html"%}
{%block title%}{{title}}{%endblock%}
{%block content%}
<div class="container-fluid w-75">
  {% for i in range(titles|length) %}
  {% if i > 0 %}
  <hr><hr>
  {% endif %}
  <div class="row my-5 align-middle">
    <div class="col-3" style="text-align:right;">
      <h1>{{ titles[i] }}</h1>
    </div>
    <div class="col-9" style="text-align:justify;" >
      {% for j in range(content[i]|length) %}
      <p>{{ content[i][j] }}</p>
      {% endfor %}
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}